# Generated by Django 4.2.20 on 2025-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telnet_host', models.CharField(max_length=100)),
                ('telnet_port', models.PositiveIntegerField()),
                ('ping_destination', models.CharField(max_length=100)),
                ('test_start', models.DateTimeField()),
                ('test_end', models.DateTimeField()),
                ('statistics', models.TextField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
