# Generated by Django 4.2.20 on 2025-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktestresult',
            name='sw_name',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
