# Generated by Django 4.2.20 on 2025-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtest', '0003_alter_networktestresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networktestresult',
            name='success',
            field=models.CharField(choices=[('FT', 'Falha Total'), ('FP', 'Falha Parcial'), ('SF', 'Sem Falha')], default='SF', max_length=2),
        ),
    ]
