# Generated by Django 4.2.20 on 2025-04-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtest', '0004_alter_networktestresult_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktestresult',
            name='test_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
