# Generated by Django 4.2.20 on 2025-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtest', '0005_networktestresult_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('device_name', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=75)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
